spring: 
  api: 
    accountdetails: 
      context-path: /CurrentAccount/{currentaccountId}/Retrieve
      hosturl: v1/bian-3/core/payment/creditor/10.0.0/
      jolt-filename: accountdetails742047-jolt.json
    beneficiaries: 
      context-path: /Beneficiaries/{currentaccountId}/Retrieve
      hosturl: v1/bian-3/core/payment/debitor/10.0.0/
      jolt-filename: Beneficiaries706153-jolt.json
    compliancecheck: 
      context-path: /RegulatoryCompliance/Evaluate
      hosturl: v1/bian-3/core/payment/creditor/10.0.0/
      jolt-filename: compliancecheck257609-jolt.json
    fundtransferinitiate: 
      context-path: /PaymentInitiation/Initiate
      hosturl: v1/bian-3/core/payment/creditor/10.0.0/
      jolt-filename: fundtransferinitiate910686-jolt.json
    panvalidation: 
      context-path: /panverification/{currentaccountId}
      hosturl: v1/bian-3/core/payment/debitor/10.0.0/
      jolt-filename: panvalidation551595-jolt.json
    paymentexecution: 
      context-path: /PaymentExecution/Initiate
      hosturl: v1/bian-3/core/payment/creditor/10.0.0/
      jolt-filename: paymentexecution574561-jolt.json
    paymentorder: 
      context-path: /PaymentOrder/Initiate
      hosturl: v1/bian-3/core/payment/creditor/10.0.0/
      jolt-filename: paymentorder142961-jolt.json
    verifyaccount: 
      context-path: /CurrentAccount/{currentaccountId}/Retrieve
      hosturl: v1/bian-3/core/payment/creditor/10.0.0/
      jolt-filename: verifyaccount375923-jolt.json
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${mysql_pwd}
    url: jdbc:mysql://${mysql_url}:3306/camunda
    username: ${mysql_user}
